### PR TITLE
Use replaceAll instead of StringUtils

### PR DESCRIPTION
**Pull request by JamoCA**
CF2023 may have removed Apache commons library

### CODE REVIEW

**Comment by kwaschny** [comment]
1. Did you test the performance difference? I wonder if one can call the native [`String.replace()`](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#replace-java.lang.CharSequence-java.lang.CharSequence-) instead? It still works in ACF ≤10, but they ruined that in ACF ≥11 by overriding it with ColdFusion's [`replace()`](https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-functions/functions-m-r/replace.html) method.

2. The `javaCast` is redundant. `trim()` already casts any simple value to `java.lang.String`.

3. Why did you only change it in `dumpmail.cfm` but not in `dump.cfm`?

**Comment by JamoCA** [comment]
1. Perf? I've encountered [intermittent hard errors](https://dev.to/gamesover/use-java-replaceall-instead-of-coldfusion-rereplacenocase-ee4) when using `replacenocase` & `replace` functions.  I've learned the hard way to not blindly trust Adobe's implementations and explicit redundancy has proven to consistently work.

2. I was unaware of that, but I'd prefer values not be blindly trimmed during string conversion.  (For example, the string `#chr(32)#test@test.com#chr(9)#` is considered a valid email because CF's isValid("email") auto-trims.)

3. I don't contribute a lot on Github and use the web interface. I couldn't figure out how to submit them both edits together.

**Comment by kwaschny** [comment]
Closing this unmerged as the changes have been commited with 89ba310c1a70f44b53e8e97a97270db8d5ab51be. Thank your for your contribution, James.

As a side note: Your blog post mentions tickets where the reporters [basically attacked themselves by using poor regular expression patterns](https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS). So Adobe is technically correct when calling them "UserError" or "AsDesigned". On the other hand, there was no good reason to take 8 years to offer a replacement for the underlying [Jakarta ORO](https://jakarta.apache.org/) engine (retried in 2010) with Java's native one (PCRE) [in ACF 2018](https://community.adobe.com/t5/coldfusion-discussions/regular-expression-enhancements-in-coldfusion-2018-release-update-5/td-p/10644940).

**Comment by JamoCA** [comment]
Thanks!  cf_dump now works with both CF2021 & CF2023 as of the update performed on Nov 27, 2023.

I didn't realize that any changes were committed as I was watching this thread for updates.  I'll download the newer version and set a watch on this project.

Thanks.

**Pull request closed without merging**
